branches:
  only:
    - gh-pages
    - /.*/
language: node_js
node_js:
  - "node"
  - "8"
  - "6"
addons:
  chrome: stable
sudo: required
before_script:
  - node_modules/.bin/gulp startServer &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
script: node_modules/.bin/gulp
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: "dist"
  on:
    branch: master
