language: node_js
node_js:
  - "stable"
  - "4.3"
  - "4.2"
before_script:
  - node_modules/gulp/bin/gulp.js startServer &
script: node_modules/gulp/bin/gulp.js clean default
after_script:
  - kill %1
